export const CREATE_PAGE_REQUEST = "CREATE_PAGE_REQUEST";
export const CREATE_PAGE_SUCCESS = "CREATE_PAGE_SUCCESS";
export const CREATE_PAGE_FAILURE = "CREATE_PAGE_FAILURE";



export const CREATE_SLIDER_REQUEST = 'CREATE_SLIDER_REQUEST';
export const CREATE_SLIDER_SUCCESS = 'CREATE_SLIDER_SUCCESS';
export const CREATE_SLIDER_FAIL = 'CREATE_SLIDER_FAIL';

export const GET_ALL_SLIDER_REQUEST = 'GET_ALL_SLIDER_REQUEST';
export const GET_ALL_SLIDER_SUCCESS = 'GET_ALL_SLIDER_SUCCESS';
export const GET_ALL_SLIDER_FAIL = 'GET_ALL_SLIDER_FAIL';
